languageCode = "en-us"
title = "HOTOSM DevOps Documentation"
theme = "book"
DefaultContentLanguage = "en"
relativeurls = true
enableGitInfo = true

[params]
    BookRepo = "https://github.com/hotosm/devops-docs"
    BookShowToC = false
    BookEditPath = "/edit/master/content/"
    matomoSiteID = 23

[imaging]
    resampleFilter = "box"
    quality = 75